resolver: lts-12.26

packages:
- .
- server
- client

extra-deps:
- extensible-effects-3.1.0.1
- extra-1.6.8
- th-format-0.1.2.0
- proteaaudio-0.7.0.1
- log-effect-1.1.1

nix:
        # pure: false
  packages:
  - mesa_noglu
  - freeglut
  - zlib
  - gmp
  - libpulseaudio
