name: stack

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.resolver }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        resolver: ["lts-14", "lts-16", "nightly"]
        cache-version: ["2021-01-08"]

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: "8.8.4"
        stack-version: "2.5.1"
        enable-stack: true

    # See: https://github.com/actions/cache/issues/445
    - name: Install GNU tar
      if: runner.os == 'macOS'
      run: |
        brew install gnu-tar
        echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH

    - name: Cache ~/.stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.resolver }}-${{ matrix.cache-version }}-stack

    - name: Install libralies (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y freeglut3-dev
    
    # - name: Install libralies (mac)
    #   if: runner.os == 'macOS'
    #   run: |
    #     brew update
    #     brew install sdl2 pkg-config sdl2_gfx sdl2_ttf

    - name: Install dependencies
      env:
        STACK_YAML: stack-${{ matrix.resolver }}.yaml
      run: stack test --only-dependencies

    - name: Build
      env:
        STACK_YAML: stack-${{ matrix.resolver }}.yaml
      run: |
        stack test --fast
        stack bench --fast
        stack install --fast
